#!/usr/bin/env python3
"""
Generate Lean code for all viable Collatz tuples up to v_strong = 8.
Outputs a single Lean file: Generated_Tuples.lean
"""

import itertools

# ==============================
# Core math utilities
# ==============================

def cycle_rhs(v):
    """Compute RHS = sum(3^(k-1-i) * 2^(sum v[0:i]))"""
    k = len(v)
    rhs = 0
    acc = 0
    for i in range(k):
        rhs += (3 ** (k - 1 - i)) * (2 ** acc)
        acc += v[i]
    return rhs

def cycle_lhs(v):
    return (2 ** sum(v)) - (3 ** len(v))

def is_viable(v):
    return cycle_lhs(v) > 0

# ==============================
# Tuple generation
# ==============================

def generate_tuples(v_strong, max_k):
    """Generate all viable tuples for given v_strong"""
    results = []
    for k in range(2, max_k + 1):
        for num_strong in range(1, k + 1):
            remaining = k - num_strong
            for num_ones in range(remaining + 1):
                num_twos = remaining - num_ones
                base = [v_strong] * num_strong + [1] * num_ones + [2] * num_twos
                for perm in set(itertools.permutations(base)):
                    if is_viable(list(perm)):
                        results.append(list(perm))
    return results

# ==============================
# MAIN GENERATION
# ==============================

MAX_V_STRONG = 8
OUTFILE = "Generated_Tuples.lean"

with open(OUTFILE, "w") as f:
    f.write("-- AUTO-GENERATED FILE — DO NOT EDIT\n")
    f.write("-- Generated by generate_tuples.py\n\n")

    for v_strong in range(3, MAX_V_STRONG + 1):
        max_k = v_strong + 3  # conservative bound
        tuples = generate_tuples(v_strong, max_k)

        f.write(f"-- v_strong = {v_strong}, total = {len(tuples)}\n")
        f.write(f"def viable_v{v_strong} : List (List Nat) := [\n")

        for t in tuples:
            f.write("  [" + ", ".join(map(str, t)) + "],\n")

        f.write("]\n\n")

print("DONE. File written to Generated_Tuples.lean")
